@apiUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoidGVzdHVzZXIiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRXWFdqRjJISG9EakFoZ1FrNVQxSi91UUtZVExZMzZuYkRSTGtGSjdqUUlYR0ZhYUZUNlNUQyIsImF2YXRhclVybCI6bnVsbCwiY3VycmVudEdpZnQiOiIiLCJob3VzZWhvbGRJZCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNS0wOS0xMVQxMTo1MzoxMC4wMDFaIiwidXBkYXRlZEF0IjoiMjAyNS0wOS0xMVQxMTo1MzoxMC4wMDFaIiwiaWF0IjoxNzU3NTkxNTk2fQ.EA43bkUvegjrTKsi82dg55HnN8mED9-uwPcXGh7DCjw
@tokenMartine = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicHNldWRvIjoidGVzdHVzZXIiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRXWFdqRjJISG9EakFoZ1FrNVQxSi91UUtZVExZMzZuYkRSTGtGSjdqUUlYR0ZhYUZUNlNUQyIsImF2YXRhclVybCI6bnVsbCwiY3VycmVudEdpZnQiOiIiLCJob3VzZWhvbGRJZCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNS0wOS0xMVQxMTo1MzoxMC4wMDFaIiwidXBkYXRlZEF0IjoiMjAyNS0wOS0xMVQxMTo1MzoxMC4wMDFaIiwiaWF0IjoxNzU3NTkxNjE0fQ.epDMtz44M1OAcpX9Myc1xMRzbV5lnuptFDZnwUb_Cu0

### User Routes
# @name createUser
POST http://localhost:3000/api/auth/local/register
Content-Type: application/json

{
  "pseudo": "testuser",
  "email": "test@example.com",
  "password": "password123"
}

### User Routes
# @name createUser
POST http://localhost:3000/api/auth/local/register
Content-Type: application/json

{
  "pseudo": "conjoint",
  "email": "martine@example.com",
  "password": "password123"
}

###
# @name loginUser
POST http://localhost:3000/api/auth/local
Content-Type: application/json

{
  "identifier": "test@example.com",
  "password": "password123"
}

###
# @name martine loginUser
POST http://localhost:3000/api/auth/local
Content-Type: application/json

{
  "identifier": "martine@example.com",
  "password": "password123"
}

### Household Routes
# @name createHousehold
POST http://localhost:3000/api/households
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "My Family",
  "avatarUrl": "https://img.favpng.com/16/11/7/gravatar-computer-icons-blog-png-favpng-Jr68yZHtrGj5dSUqHSXaJDQ4f.jpg"
}

###
# @name getHouseholdById
GET http://localhost:3000/api/households/1
Authorization: Bearer {{token}}

###
# @name updateHousehold
PUT http://localhost:3000/api/households/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Family",
  "avatarUrl": "https://img.favpng.com/16/11/7/gravatar-computer-icons-blog-png-favpng-Jr68yZHtrGj5dSUqHSXaJDQ4f.jpg"
}

###
# @name joinHousehold
POST http://localhost:3000/api/households/1/join
Content-Type: application/json
Authorization: Bearer {{tokenMartine}}

###
# @name leaveHousehold
POST http://localhost:3000/api/households/1/leave
Content-Type: application/json
Authorization: Bearer {{tokenMartine}}


### Task Routes

# @name createTask
POST http://localhost:3000/api/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Clean the kitchen",
  "repetition": 7, 
  "dueDate": "2025-09-15T10:00:00Z",
  "deactivated": false,
  "xp": 50
}

###
# @name getAllTasks
GET http://localhost:3000/api/tasks
Authorization: Bearer {{token}}

###
# @name getTaskById
GET http://localhost:3000/api/tasks/1
Authorization: Bearer {{token}}

###
# @name updateTask
PUT http://localhost:3000/api/tasks/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Clean the bathroom",
  "repetition": 14, 
  "dueDate": "2025-09-20T12:00:00Z",
  "deactivated": false,
  "xp": 75,
  "householdId": 1
}

###
# @name deleteTask
DELETE http://localhost:3000/api/tasks/1
Authorization: Bearer {{token}}

### Me

# @name getMe
GET http://localhost:3000/api/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "pseudo": "testuser",
  "avatarUrl": "https://example.com/avatar.jpg"
}

###
# @name updateMe
PUT http://localhost:3000/api/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "pseudo": "updateduser",
  "avatarUrl": "https://example.com/new-avatar.jpg"
}

###
# @name updateGift
PUT http://localhost:3000/api/me/gift
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "New Gift Title"
}

### CompletedTask Routes

# @name createCompletedTask
POST http://localhost:3000/api/completedtask
Content-Type: application/json

{
  "xpEarned": 50,
  "taskId": 1
}

###
# @name getAll Tasks To complete
GET http://localhost:3000/api/tasks/to-complete
Authorization: Bearer {{token}}

###
# @name getCompletedTaskById
GET http://localhost:3000/api/completedtask/1

###
# @name updateCompletedTask
PUT http://localhost:3000/api/completedtask/1
Content-Type: application/json

{
  "xpEarned": 60,
  "taskId": 1,
  "userId": 1
}

###
# @name deleteCompletedTask
DELETE http://localhost:3000/api/completedtask/1